export const MODULE_NAME = 'CLIENT';

export const ACTION_TYPES = {
    FETCH_MANY_CLIENTS: 'FETCH_MANY_CLIENTS',
    SAVE_MANY_CLIENTS: 'SAVE_MANY_CLIENTS',
    FETCH_ONE_CLIENT: 'FETCH_ONE_CLIENT',
    SAVE_ONE_CLIENT: 'SAVE_ONE_CLIENT',
    CREATE_ONE_CLIENT: 'CREATE_ONE_CLIENT',
    UPDATE_ONE_CLIENT: 'UPDATE_ONE_CLIENT',
    DELETE_ONE_CLIENT: 'DELETE_ONE_CLIENT',
    DELETE_SAVE_ONE_CLIENT: 'DELETE_SAVE_ONE_CLIENT',
    FETCH_FAILED_CLIENT: 'FETCH_FAILED_CLIENT',
};
