/**
 * Broker
 * Broker API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resource containing information of a broker
 */
export interface Broker { 
    id?: number;
    fname?: string;
    lname?: string;
    email?: string;
    password?: string;
    createdAt?: string;
    updatedAt?: string;
}

