/**
 * Broker
 * Broker API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resource containing request body for broker login request
 */
export interface BrokerLoginObject { 
    email?: string;
    password?: string;
}

