/**
 * Broker
 * Broker API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Resource containing authenticated user details
 */
export interface Client { 
    id?: number;
    fname?: string;
    lname?: string;
    createdAt?: string;
    updatedAt?: string;
    amount?: number;
    rate?: number;
    amortization?: number;
    brokerId?: number;
}

