/**
 * Broker
 * Broker API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorObject } from './errorObject';


/**
 * Generic error response object
 */
export interface ErrorResponse { 
    errors: Array<ErrorObject>;
}

