/**
 * Broker
 * Broker API
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The root of the PostResponseObject type\'s schema.
 */
export interface PostResponseObject { 
    /**
     * Unique identified for the created object
     */
    id?: string;
    /**
     * Created object
     */
    content?: object;
}

