export const MODULE_NAME = 'BROKER';

export const ACTION_TYPES = {
    LOG_IN_BROKER: 'LOG_IN_BROKER',
    SAVE_ONE_BROKER: 'SAVE_ONE_BROKER',
    CREATE_ONE_BROKER: 'CREATE_ONE_BROKER',
    LOG_OUT_BROKER: 'LOG_OUT_BROKER',
    FETCH_FAILED_BROKER: 'FETCH_FAILED_BROKER',
};
